// <auto-generated />
using System;
using Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Prn222AssigmentContext))]
    [Migration("20260715040049_AddSubscriptionAndMomo")]
    partial class AddSubscriptionAndMomo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Models.SubscriptionPackage", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<string>("DurationUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Month");

                    b.Property<int>("DurationValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ExtraTokenAmount")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PackageId");

                    b.ToTable("SubscriptionPackages");
                });

            modelBuilder.Entity("DataAccessLayer.Models.UserTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("MoMo");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTransactions");
                });

            modelBuilder.Entity("Domain.Models.Aimodel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ModelId")
                        .HasName("PK__AIModels__E8D7A12CCEA820F1");

                    b.HasIndex(new[] { "ModelName" }, "UQ__AIModels__67DC63B557FFC277")
                        .IsUnique();

                    b.ToTable("AIModels", (string)null);
                });

            modelBuilder.Entity("Domain.Models.BenchmarkResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<double?>("AnswerRelevanceScore")
                        .HasColumnType("float");

                    b.Property<double?>("ContextPrecisionScore")
                        .HasColumnType("float");

                    b.Property<double?>("ContextRecallScore")
                        .HasColumnType("float");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("int");

                    b.Property<double?>("FaithfulnessScore")
                        .HasColumnType("float");

                    b.Property<string>("GeneratedResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LatencyMilliseconds")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("TokensIn")
                        .HasColumnType("int");

                    b.Property<int?>("TokensOut")
                        .HasColumnType("int");

                    b.HasKey("ResultId")
                        .HasName("PK__Benchmar__976902086927374A");

                    b.HasIndex(new[] { "ExperimentId" }, "IX_BenchmarkResults_ExperimentId");

                    b.HasIndex(new[] { "QuestionId" }, "IX_BenchmarkResults_QuestionId");

                    b.ToTable("BenchmarkResults");
                });

            modelBuilder.Entity("Domain.Models.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ChapterId")
                        .HasName("PK__Chapters__0893A36A66468F12");

                    b.HasIndex("SubjectId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Domain.Models.ChatCitation", b =>
                {
                    b.Property<int>("CitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitationId"));

                    b.Property<int>("ChunkId")
                        .HasColumnType("int");

                    b.Property<int>("HistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("Snippet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CitationId")
                        .HasName("PK__ChatCita__EAD2ADFB28D54548");

                    b.HasIndex("ChunkId");

                    b.HasIndex(new[] { "HistoryId" }, "IX_ChatCitations_HistoryId");

                    b.ToTable("ChatCitations");
                });

            modelBuilder.Entity("Domain.Models.ChatHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("BotResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StandaloneQuery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("TokensIn")
                        .HasColumnType("int");

                    b.Property<int?>("TokensOut")
                        .HasColumnType("int");

                    b.Property<string>("UserMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HistoryId")
                        .HasName("PK__ChatHist__4D7B4ABD3F92A37D");

                    b.HasIndex(new[] { "SessionId" }, "IX_ChatHistories_SessionId");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("Domain.Models.ChatSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ConversationSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Cuộc trò chuyện mới");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SessionId")
                        .HasName("PK__ChatSess__C9F49290606518BF");

                    b.HasIndex("SubjectId");

                    b.HasIndex(new[] { "UserId", "LastUpdatedAt" }, "IX_ChatSessions_UserId_LastUpdated")
                        .IsDescending(false, true);

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("Domain.Models.ChunkingStrategy", b =>
                {
                    b.Property<int>("StrategyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StrategyId"));

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StrategyId")
                        .HasName("PK__Chunking__459B986C5A88EF21");

                    b.HasIndex(new[] { "StrategyName" }, "UQ__Chunking__E7BA90D15C882147")
                        .IsUnique();

                    b.ToTable("ChunkingStrategies");
                });

            modelBuilder.Entity("Domain.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("FileHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("DocumentId")
                        .HasName("PK__Document__1ABEEF0F53005A57");

                    b.HasIndex("UploadedBy");

                    b.HasIndex(new[] { "ChapterId" }, "IX_Documents_ChapterId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Domain.Models.DocumentChunk", b =>
                {
                    b.Property<int>("ChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChunkId"));

                    b.Property<int>("ChunkOrder")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingVector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasEmbedding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("IndexId")
                        .HasColumnType("int");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int>("TokenCount")
                        .HasColumnType("int");

                    b.Property<string>("VectorStoreKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ChunkId")
                        .HasName("PK__Document__FBFF9D0012F19D2C");

                    b.HasIndex(new[] { "IndexId" }, "IX_DocumentChunks_IndexId");

                    b.HasIndex(new[] { "IndexId", "ChunkOrder" }, "UC_Index_ChunkOrder")
                        .IsUnique();

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("Domain.Models.DocumentIndex", b =>
                {
                    b.Property<int>("IndexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndexId"));

                    b.Property<int>("ChunkOverlap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<int>("ChunkSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(500);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("StrategyId")
                        .HasColumnType("int");

                    b.HasKey("IndexId")
                        .HasName("PK__Document__40BC8A4147AD88D9");

                    b.HasIndex("ModelId");

                    b.HasIndex("StrategyId");

                    b.HasIndex(new[] { "DocumentId" }, "IX_DocumentIndexes_DocumentId");

                    b.HasIndex(new[] { "DocumentId", "ModelId", "StrategyId", "ChunkSize", "ChunkOverlap" }, "UC_Doc_Model_Strat_Size_Overlap")
                        .IsUnique();

                    b.ToTable("DocumentIndexes");
                });

            modelBuilder.Entity("Domain.Models.EmbeddingModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ModelId")
                        .HasName("PK__Embeddin__E8D7A12C85EB7DA4");

                    b.HasIndex(new[] { "ModelName" }, "UQ__Embeddin__67DC63B57E076D19")
                        .IsUnique();

                    b.ToTable("EmbeddingModels");
                });

            modelBuilder.Entity("Domain.Models.Experiment", b =>
                {
                    b.Property<int>("ExperimentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExperimentId"));

                    b.Property<int>("AimodelId")
                        .HasColumnType("int")
                        .HasColumnName("AIModelId");

                    b.Property<int?>("ChunkOverlap")
                        .HasColumnType("int");

                    b.Property<int?>("ChunkSize")
                        .HasColumnType("int");

                    b.Property<int?>("EmbeddingModelId")
                        .HasColumnType("int");

                    b.Property<string>("ExperimentDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExperimentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("StrategyId")
                        .HasColumnType("int");

                    b.HasKey("ExperimentId")
                        .HasName("PK__Experime__7372232CA8244F24");

                    b.HasIndex("AimodelId");

                    b.HasIndex("EmbeddingModelId");

                    b.HasIndex("StrategyId");

                    b.HasIndex(new[] { "ExperimentName" }, "UQ__Experime__C12C9438FD53F0D9")
                        .IsUnique();

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("Domain.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int?>("DefaultChunkOverlap")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultChunkSize")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultModelId")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultStrategyId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subjects__AC1BA3A8AF32ACA7");

                    b.HasIndex(new[] { "SubjectCode" }, "UQ__Subjects__9F7CE1A9B0A9231D")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Domain.Models.SubjectTeacher", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSubjectHead")
                        .HasColumnType("bit");

                    b.HasKey("SubjectId", "UserId")
                        .HasName("PK_SubjectTeachers");

                    b.HasIndex("UserId");

                    b.ToTable("SubjectTeachers", (string)null);
                });

            modelBuilder.Entity("Domain.Models.TestSet", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("GroundTruth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId")
                        .HasName("PK__TestSets__0DC06FAC4229D7D8");

                    b.HasIndex("SubjectId");

                    b.ToTable("TestSets");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PurchasedTokenBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("PurchasedTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Student");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WeeklyTokenLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(250000);

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CDB9FB20B");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4E3098676")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105349D8CA7DF")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAccessLayer.Models.UserTransaction", b =>
                {
                    b.HasOne("DataAccessLayer.Models.SubscriptionPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.BenchmarkResult", b =>
                {
                    b.HasOne("Domain.Models.Experiment", "Experiment")
                        .WithMany("BenchmarkResults")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Benchmark__Exper__7C4F7684");

                    b.HasOne("Domain.Models.TestSet", "Question")
                        .WithMany("BenchmarkResults")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Benchmark__Quest__7B5B524B");

                    b.Navigation("Experiment");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Models.Chapter", b =>
                {
                    b.HasOne("Domain.Models.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Chapters__Subjec__403A8C7D");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Domain.Models.ChatCitation", b =>
                {
                    b.HasOne("Domain.Models.DocumentChunk", "Chunk")
                        .WithMany("ChatCitations")
                        .HasForeignKey("ChunkId")
                        .IsRequired()
                        .HasConstraintName("FK__ChatCitat__Chunk__6E01572D");

                    b.HasOne("Domain.Models.ChatHistory", "History")
                        .WithMany("ChatCitations")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChatCitat__Histo__6D0D32F4");

                    b.Navigation("Chunk");

                    b.Navigation("History");
                });

            modelBuilder.Entity("Domain.Models.ChatHistory", b =>
                {
                    b.HasOne("Domain.Models.ChatSession", "Session")
                        .WithMany("ChatHistories")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChatHisto__Sessi__6A30C649");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Domain.Models.ChatSession", b =>
                {
                    b.HasOne("Domain.Models.Subject", "Subject")
                        .WithMany("ChatSessions")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__ChatSessi__Subje__66603565");

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ChatSessi__UserI__656C112C");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Document", b =>
                {
                    b.HasOne("Domain.Models.Chapter", "Chapter")
                        .WithMany("Documents")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Documents__Chapt__4F7CD00D");

                    b.HasOne("Domain.Models.User", "UploadedByNavigation")
                        .WithMany("Documents")
                        .HasForeignKey("UploadedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Documents__Uploa__5070F446");

                    b.Navigation("Chapter");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("Domain.Models.DocumentChunk", b =>
                {
                    b.HasOne("Domain.Models.DocumentIndex", "Index")
                        .WithMany("DocumentChunks")
                        .HasForeignKey("IndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DocumentC__Index__5EBF139D");

                    b.Navigation("Index");
                });

            modelBuilder.Entity("Domain.Models.DocumentIndex", b =>
                {
                    b.HasOne("Domain.Models.Document", "Document")
                        .WithMany("DocumentIndices")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DocumentI__Docum__5812160E");

                    b.HasOne("Domain.Models.EmbeddingModel", "Model")
                        .WithMany("DocumentIndices")
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("FK__DocumentI__Model__59063A47");

                    b.HasOne("Domain.Models.ChunkingStrategy", "Strategy")
                        .WithMany("DocumentIndices")
                        .HasForeignKey("StrategyId")
                        .IsRequired()
                        .HasConstraintName("FK__DocumentI__Strat__59FA5E80");

                    b.Navigation("Document");

                    b.Navigation("Model");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("Domain.Models.Experiment", b =>
                {
                    b.HasOne("Domain.Models.Aimodel", "Aimodel")
                        .WithMany("Experiments")
                        .HasForeignKey("AimodelId")
                        .IsRequired()
                        .HasConstraintName("FK__Experimen__AIMod__75A278F5");

                    b.HasOne("Domain.Models.EmbeddingModel", "EmbeddingModel")
                        .WithMany("Experiments")
                        .HasForeignKey("EmbeddingModelId")
                        .HasConstraintName("FK__Experimen__Embed__76969D2E");

                    b.HasOne("Domain.Models.ChunkingStrategy", "Strategy")
                        .WithMany("Experiments")
                        .HasForeignKey("StrategyId")
                        .HasConstraintName("FK__Experimen__Strat__778AC167");

                    b.Navigation("Aimodel");

                    b.Navigation("EmbeddingModel");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("Domain.Models.SubjectTeacher", b =>
                {
                    b.HasOne("Domain.Models.Subject", "Subject")
                        .WithMany("SubjectTeachers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SubjectTeachers_Subjects");

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SubjectTeachers_Users");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.TestSet", b =>
                {
                    b.HasOne("Domain.Models.Subject", "Subject")
                        .WithMany("TestSets")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TestSets__Subjec__71D1E811");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Domain.Models.Aimodel", b =>
                {
                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("Domain.Models.Chapter", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Domain.Models.ChatHistory", b =>
                {
                    b.Navigation("ChatCitations");
                });

            modelBuilder.Entity("Domain.Models.ChatSession", b =>
                {
                    b.Navigation("ChatHistories");
                });

            modelBuilder.Entity("Domain.Models.ChunkingStrategy", b =>
                {
                    b.Navigation("DocumentIndices");

                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("Domain.Models.Document", b =>
                {
                    b.Navigation("DocumentIndices");
                });

            modelBuilder.Entity("Domain.Models.DocumentChunk", b =>
                {
                    b.Navigation("ChatCitations");
                });

            modelBuilder.Entity("Domain.Models.DocumentIndex", b =>
                {
                    b.Navigation("DocumentChunks");
                });

            modelBuilder.Entity("Domain.Models.EmbeddingModel", b =>
                {
                    b.Navigation("DocumentIndices");

                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("Domain.Models.Experiment", b =>
                {
                    b.Navigation("BenchmarkResults");
                });

            modelBuilder.Entity("Domain.Models.Subject", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("ChatSessions");

                    b.Navigation("SubjectTeachers");

                    b.Navigation("TestSets");
                });

            modelBuilder.Entity("Domain.Models.TestSet", b =>
                {
                    b.Navigation("BenchmarkResults");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
